spring:
  application:
    name: load-balancer
  main:
    allow-circular-references: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.client: DEBUG
