spring:
  application:
    name: pessoas
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
      data-locations: classpath:data.sql